image:
- macOS
- Ubuntu
- Visual Studio 2019

skip_branch_with_pr: true
stack: python 3.11,

platform:
  - x64

environment:
  GITHUB_TOKEN:
    secure: 0opxPJDxYM2CNHw/RVWThRvmUGr/pK6JAxVPh60uFxklz7OGHAD1GHbJh8r80Iot

install:
- pip install -r requirements.txt

build_script:
- flet pack flet_ui.py --name tcuClassRober --product-name counter --add-data "assets:assets"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  draft: true
  prerelease: false
  force_update: true
  description: "just test"
  on:
    branch: main
  appveyor_repo_tag: true
#
#
#   Windows package
# 
for:

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf counter-macos.tar.gz -C dist tcuClassRober.app

  artifacts:
  - path: counter-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf counter-linux.tar.gz -C dist tcuClassRober 

  artifacts:
  - path: counter-linux.tar.gz

-
  matrix:
    only:
    - image: Visual Studio 2019

  build_script:
  - flet pack flet_ui.py --name tcuClassRober --product-name counter --add-data "assets;assets"

  after_build:
  - 7z a counter-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: counter-windows.zip
