image:
- macOS
- Ubuntu
- Visual Studio 2022

skip_branch_with_pr: true
stack: python 3.11.7,

platform:
  - x64

environment:
  GITHUB_TOKEN:
    secure: bH1FnDt1qt/u4pifPDnTRKXeqDo4G2TqwTLLOjD7FU9F2YUaR8wMtn8rLuJCr74w

install:
- pip install -r requirements.txt

build_script:
- flet pack flet_ui.py --name tcuClassRober --product-name tcuClassRober --add-data "assets:assets"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  draft: true
  prerelease: false
  force_update: true
  description: "此為測試版本，功能尚未完全"
  on:
    branch: main
  appveyor_repo_tag: true
#
#
#   Windows package
# 
for:

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf tcuClassRober-macos.tar.gz -C dist tcuClassRober

  artifacts:
  - path: tcuClassRober-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf tcuClassRober-linux.tar.gz -C dist tcuClassRober 

  artifacts:
  - path: tcuClassRober-linux.tar.gz

-
  matrix:
    only:
    - image: Visual Studio 2019

  build_script:
  - flet pack flet_ui.py --name tcuClassRober --product-name tcuClassRober --add-data "assets;assets"

  after_build:
  - 7z a tcuClassRober-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: tcuClassRober-windows.zip
