image:
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.11,

environment:
  GITHUB_TOKEN:
    secure: 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

install:
- pip install -r requirements.txt

build_script:
- flet pack flet_ui.py --name tcuClassRober --product-name counter --add-data "assets:assets"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  draft: true
  prerelease: false
  force_update: true
  description: "just test"
  on:
    branch: main
  appveyor_repo_tag: true
#
#
#   Windows package
# 
for:

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf counter-macos.tar.gz -C dist tcuClassRober.app

  artifacts:
  - path: counter-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf counter-linux.tar.gz -C dist tcuClassRober 

  artifacts:
  - path: counter-linux.tar.gz

